version: '3.7'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx/
        ports:
            - '80:80'
        expose:
            - 80
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /app
        user: ${CURRENT_USER:-0}
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
        volumes:
            - ./:/app
        depends_on:
            - database
        env_file:
            - .env

    database:
        image: 'mysql:5.7'
        environment:
            - MYSQL_DATABASE=${CONFIG_MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${CONFIG_MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql/data:/var/lib/mysql

    wait:
        image: dokku/wait
